# Generated by Django 4.1.7 on 2023-03-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_remove_userpassword_encrypted_password_and_more'),
        ('accounts', '0002_alter_actionlogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwords.profile', verbose_name='Profile'),
        ),
    ]
