# Generated by Django 4.1.7 on 2023-03-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_actionlogs_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlogs',
            old_name='user',
            new_name='profile',
        ),
    ]
