# Generated by Django 4.1.7 on 2023-03-27 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import passwords.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_password', models.TextField(verbose_name='Website password')),
                ('website_name', models.TextField(null=True, verbose_name='Name of website')),
                ('website_link', models.TextField(null=True, verbose_name='URL to website')),
                ('website_username', models.TextField(null=True, verbose_name='Login on the website')),
                ('website_notes', models.TextField(null=True, verbose_name='Website notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User password',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_password', models.TextField(null=True, verbose_name='Master password')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=passwords.models.upload_to, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
