# Generated by Django 4.1.7 on 2023-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.TextField(verbose_name='Secret key for decryption'),
        ),
    ]
