# Generated by Django 4.1.7 on 2023-03-16 09:25

from django.db import migrations, models
import passwords.models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_alter_profile_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=passwords.models.upload_to, verbose_name='Avatar'),
        ),
    ]
