# Generated by Django 4.1.7 on 2023-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='category',
        ),
        migrations.AddField(
            model_name='userpassword',
            name='website_link',
            field=models.TextField(null=True, verbose_name='URL to website'),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='website_name',
            field=models.TextField(null=True, verbose_name='Name of website'),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='website_notes',
            field=models.TextField(null=True, verbose_name='Website notes'),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='website_username',
            field=models.TextField(null=True, verbose_name='Login on the website'),
        ),
        migrations.DeleteModel(
            name='PasswordCategory',
        ),
    ]
