# Generated by Django 4.1.7 on 2023-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_remove_userpassword_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='master_password',
            field=models.TextField(null=True, verbose_name='Master password'),
        ),
    ]
