# Generated by Django 4.1.7 on 2023-03-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_remove_profile_secret_key_profile_master_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='userpassword',
            name='website_password',
            field=models.TextField(default=2, verbose_name='Website password'),
            preserve_default=False,
        ),
    ]
